name = "TabularTDLearning"
uuid = "df77095f-98f0-51e5-a706-d0ff5a5ad33f"
license = "MIT"
repo = "https://github.com/JuliaPOMDP/TabularTDLearning.jl"
version = "0.4.5"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataStructures = "0.18"
POMDPLinter = "0.1"
POMDPTools = "0.1, 1"
POMDPs = "0.9, 1"
julia = "1.3"
